service:
  name: error-scanner

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  profile: personal

functions:
  run:
    handler: errorScanner.run
    events:
      - schedule: rate(1 hour)